blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView


app_name = 'blog'

urlpatterns = [
    path('list/', BlogListView.as_view(), name='list-view'),
    path('detail/<slug:slug>/', BlogDetailView.as_view(), name='detail-view'),
]

portfolio/urls.py
from django.urls import path

from portfolio.views import (
    PortfolioListView,
    PortfolioDetailView,
    MyCVDetailView,
)


app_name = 'portfolio'

urlpatterns = [
    path('list/', PortfolioListView.as_view(), name='list-view'),
    path('detail/<slug:slug>/', PortfolioDetailView.as_view(), name='detail-view'),
    # path('<slug:slug>/', MyCVDetailView.as_view(), name='cv-view'),
]

portfolio/models/CV.py
from django.db import models

from ckeditor.fields import RichTextField


class CV(models.Model):
    slug = models.SlugField(max_length=200)
    body = RichTextField()
    date = models.DateTimeField()

    def __str__(self):
        return self.slug

portfolio/models/branch.py
from django.db import models


class Branch(models.Model):
    name = models.CharField(max_length=128)
    data_filter = models.CharField(
        max_length=128,
        help_text="change fild name space to hiphen",
    )
    date = models.DateTimeField()

    def __str__(self):
        return f"{self.name}"

portfolio/models/portfolio.py
from django.db import models

from ckeditor.fields import RichTextField


class Portfolio(models.Model):
    slug = models.SlugField(max_length=200)
    iamge = models.ImageField()
    title = models.CharField(max_length=80)
    short_description = models.CharField(max_length=255)
    description = RichTextField()
    customer_opinion = models.CharField(max_length=300)
    branch = models.ForeignKey(
        'portfolio.Branch',
        null=True,
        on_delete=models.SET_NULL
    )
    date = models.DateTimeField()

    def __str__(self):
        return f"{self.title}"

portfolio/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from portfolio.models.portfolio import Portfolio
from portfolio.models.CV import CV


class PortfolioListView(ListView):
    model = Portfolio
    paginate_by = 12
    ordering = ['-date']
    template_name = "portfolio/list_view.html"


class PortfolioDetailView(DetailView):
    model = Portfolio
    template_name = 'portfolio/detail_view.html'


class MyCVDetailView(DetailView):
    model = CV
    template_name = 'portfolio/cv_view.html'

portfolio/templates/portfolio/cv_view.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/portfolio.css' %}">
{% endblock style %}

{% block main %}
<div id="cv-detail">
    <div class="container">
        <div class="flexbox">
            <div class="cv">
                <div class="cv__body" >
                    {{ object.body | safe}}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

portfolio/templates/portfolio/detail_view.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/portfolio.css' %}">
{% endblock style %}

{% block main %}
<div id="portfolio-detail">
    <div class="container">
        <div class="flexbox">
            <div class="portfolio">
                <div class="portfolio__title">
                    <h4>{{ object.title }}</h4>
                </div>
                <div class="portfolio__discription" >
                    {{ object.short_description }}
                </div>
                <img src="{{ object.iamge.url }}" /><br />
                <div class="portfolio__body" >
                    {{ object.description | safe}}
                </div>
                {% if object.customer_opinion %}
                <div class="portfolio__customer-opinion">
                    <h3>customer opinion</h3>
                    {{ object.customer_opinion }}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock main %}

portfolio/templates/portfolio/list_view.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/portfolio.css' %}">
{% endblock style %}

{% block main %}
<div id="portfolio-list">
    <div class="container">
        {% for item in object_list %}
        <div class="item">
            <div class="item__image">
                <img src="{{ item.iamge.url }}" />
            </div>
            <div class="item__text-content">
                <div class="item__title">
                    <h4><a href="{% url 'portfolio:detail-view' item.slug %}">{{ item.title }}</a></h4>
                </div>
                <div class="item__discription">
                    <p>{{ item.short_description }}</p>
                </div>
            </div>
        </div>
        {% endfor %}

        <div class="pagination">
            {% if is_paginated %}
            <ul class="pagination__list">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}"><i class="lni lni-chevron-left"></i></a></li>
                {% else %}
                    <li class="disabled"><span><i class="lni lni-chevron-left"></i></span></li>
                {% endif %}

                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li><span>{{ i }} </span></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}"><i class="lni lni-chevron-right"></i></a></li>
                {% else %}
                    <li class="disabled"><span><i class="lni lni-chevron-right"></i></span></li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock main %}