blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView


app_name = 'blog'

urlpatterns = [
    path('list/', BlogListView.as_view(), name='list-view'),
    path('detail/<slug:slug>/', BlogDetailView.as_view(), name='detail-view'),
]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Article(models.Model):
    slug = models.SlugField(max_length=200)
    title = models.CharField(max_length=120)
    thumbnail = models.ImageField()
    discription = models.CharField(max_length=355)
    body = RichTextField()
    date = models.DateTimeField()

    def __str__(self):
        return self.title

blog/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from blog.models import Article


class BlogListView(ListView):
    model = Article
    template_name = 'blog/list_view.html'
    paginate_by = 12
    ordering = ['-date']


class BlogDetailView(DetailView):
    model = Article
    template_name = 'blog/detail_view.html'

blog/templates/blog/detail_view.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">
{% endblock style %}

{% block main %}
<div id="blog-detail">
    <div class="container">
        <div class="flexbox">
            <div class="article">
                <div class="article__title">
                    <h4>{{ object.title }}</h4>
                </div>
                <div class="article__discription" >
                    {{ object.discription }}
                </div>
                <img src="{{ object.thumbnail.url }}" /><br />
                <div class="article__body" >
                    {{ object.body | safe}}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

blog/templates/blog/list_view.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">
{% endblock style %}

{% block main %}
<div id="blog-list">
    <div class="container">
        {% for item in object_list %}
        <div class="item">
            <div class="item__image">
                <img src="{{ item.thumbnail.url }}" />
            </div>
            <div class="item__text-content">
                <div class="item__title">
                    <h4><a href="{% url 'blog:detail-view' item.slug %}">{{ item.title }}</a></h4>
                </div>
                <div class="item__discription">
                    <p>{{ item.discription }}</p>
                </div>
            </div>
        </div>
        {% empty %}
            there is no article
        {% endfor %}

        <div class="pagination">
            {% if is_paginated %}
            <ul class="pagination__list">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}"><i class="lni lni-chevron-left"></i></a></li>
                {% else %}
                    <li class="disabled"><span><i class="lni lni-chevron-left"></i></span></li>
                {% endif %}

                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li><span>{{ i }} </span></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}"><i class="lni lni-chevron-right"></i></a></li>
                {% else %}
                    <li class="disabled"><span><i class="lni lni-chevron-right"></i></span></li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock main %}

{% block scripts %}{% endblock scripts %}